local gc = game.translate_string
local blue_clr = utils_xml.get_color("d_blue")
local red_clr = strformat("%c[%s,%s,%s,%s]", 255, 250, 50, 50)
local teal_clr = strformat("%c[%s,%s,%s,%s]", 255, 150, 250, 240)		-- for non-stat properties
local green_clr = utils_xml.get_color("d_green")
local def_clr  = utils_xml.get_color("ui_gray_2")
local title_clr = utils_xml.get_color("ui_gray_3")


local mcm_hp = aaa_descr_override_mcm.get_config("hp")
local mcm_rad = aaa_descr_override_mcm.get_config("rad")
local mcm_sat = aaa_descr_override_mcm.get_config("sat")
local mcm_sleep = aaa_descr_override_mcm.get_config("sleep")
local mcm_thirst = aaa_descr_override_mcm.get_config("thirst")
local mcm_alcohol = aaa_descr_override_mcm.get_config("alcohol")

local mcm_hp_t = aaa_descr_override_mcm.get_config("hp_t")
local mcm_rad_t = aaa_descr_override_mcm.get_config("rad_t")
local mcm_bleed_t = aaa_descr_override_mcm.get_config("bleed_t")

local bhs_display_numeric_at = aaa_descr_override_mcm.get_config("bhs_num_at")
local bhs_show_numeric_always = aaa_descr_override_mcm.get_config("bhs_num_always")
local bhs_show_timed_heal_time = aaa_descr_override_mcm.get_config("bhs_timed")


local dbg = false
function pr(...)
	if not dbg then return end
	printf(...)
end

obj_desc_def = ui_item.get_obj_desc
function ui_item.get_obj_desc(obj)
	if not obj then
		return ""
	end

	-- exclude non-consumables
	local sec = obj:section()
	if not (IsItem("consumable", sec)) then
		return obj_desc_def(obj)
	end

	-- exclude repair items and addons (scopes etc)
	local kind = ini_sys:r_string_ex(sec, "kind")
	if kind and (kind == "i_repair" or kind == "w_misc") then
		return obj_desc_def(obj)
	end


	local str = gc(ini_sys:r_string_ex(sec, "description"))
	-- leave only footer's real description
	local _, n_idx = string.find(str, "\\n")
	local res = string.sub(str, 1, n_idx)
	res = res .. " \\n"
	res = ui_item.item_description(obj, res)

	return res
end

BuildFooter = ui_item.build_desc_footer
function ui_item.build_desc_footer(obj, sec, str)
	str = str or gc(ini_sys:r_string_ex(sec, "description"))
	if (not str) then return "" end

	if not db.actor then
		return BuildFooter(obj, sec, str)
	end

	-- exclude non-consumables
	if not (IsItem("consumable", sec)) then
		return BuildFooter(obj, sec, str)
	end

	-- exclude repair items
	local kind = ini_sys:r_string_ex(sec, "kind")
	if kind and (kind == "i_repair" or kind == "w_misc") then
		return BuildFooter(obj, sec, str)
	end


	-- fill new properties
	local rad_max = 3870
	local boost_time = ini_sys:r_float_ex(sec, "boost_time")


	----------- instant effects -----------

	-- instant title
	local eat_health = ini_sys:r_float_ex(sec, "eat_health")
	local eat_hp_ex = mcm_hp and eat_health and eat_health ~= 0

	local eat_rad = ini_sys:r_float_ex(sec, "eat_radiation")
	local eat_rad_ex = mcm_rad and eat_rad and eat_rad ~= 0

	local eat_sat = ini_sys:r_float_ex(sec, "eat_satiety")
	local eat_sat_ex = mcm_sat and eat_sat and eat_sat ~= 0

	local eat_sleepiness = ini_sys:r_float_ex(sec, "eat_sleepiness")
	local eat_sleep_ex = mcm_sleep and eat_sleepiness and eat_sleepiness ~= 0

	local eat_thirstiness = ini_sys:r_float_ex(sec, "eat_thirstiness")
	local eat_thirst_ex = mcm_thirst and eat_thirstiness and eat_thirstiness ~= 0

	local eat_alcohol = ini_sys:r_float_ex(sec, "eat_alcohol")
	local eat_alc_ex = mcm_alcohol and eat_alcohol and eat_alcohol ~= 0

	if (eat_hp_ex or eat_rad_ex or eat_sat_ex or eat_sleep_ex or eat_thirst_ex or eat_alc_ex) then
		str = str .. title_clr .. gc("desc_over_prop") .. def_clr .. " \\n"
	end

	-- health
	if eat_hp_ex then
		local hp_clr = eat_health > 0 and green_clr or red_clr
		local hp_sign = eat_health > 0 and "+" or ""
		local hp_num = eat_health * 100
		str = str .. hp_clr .. "  • " .. def_clr .. " " .. gc("desc_over_hp") .. " " .. hp_clr .. hp_sign .. round(hp_num) .. "%" .. def_clr .. " \\n"
		pr("show health")
	end

	-- radiation
	if eat_rad_ex then
		local rad_clr = eat_rad > 0 and red_clr or green_clr
		local rad_sign = eat_rad > 0 and "+" or ""
		local rad_num = eat_rad * rad_max
		str = str .. rad_clr .. "  • " .. def_clr .. " " .. gc("desc_over_rad") .. " " .. rad_clr .. rad_sign .. round(rad_num) .. " " .. def_clr .. gc("st_msv") .. " \\n"
		pr("show rad")
	end

	-- satiety
	if eat_sat_ex then
		local sat_clr = eat_sat > 0 and green_clr or red_clr
		local sat_sign = eat_sat > 0 and "+" or ""
		local conditions = db.actor:cast_Actor():conditions()
		local red_icon_satiety = conditions:SatietyCritical() * 0.5
		local max_satiety = 1 - red_icon_satiety
		local sat_num = eat_sat / max_satiety * 100
		str = str .. sat_clr .. "  • " .. def_clr .. " " .. gc("desc_over_sat") .. " " .. sat_clr .. sat_sign .. round(sat_num) .. "%" .. def_clr .. " \\n"
		pr("show sat")
	end

	-- sleep
	local max_sleep = get_local_val([[gamedata\scripts\actor_status_sleep.script]], "actor_status_sleep", "local start_blur_4") or 8750
	local sleep_mult = get_local_val([[gamedata\scripts\actor_status_sleep.script]], "actor_status_sleep", "local eat_sleepiness_mul") or 1000
	if eat_sleep_ex then
		eat_sleepiness = eat_sleepiness * sleep_mult
		local sleep_clr = eat_sleepiness > 0 and red_clr or green_clr
		local sleep_sign = eat_sleepiness > 0 and "+" or ""
		local sleep_num = (eat_sleepiness / max_sleep) * 100
		str = str .. sleep_clr .. "  • " .. def_clr .. " " .. gc("desc_over_sleep") .. " " .. sleep_clr .. sleep_sign .. round(sleep_num) .. "%" .. def_clr .. " \\n"
		pr("show sleep")
	end

	-- thirst
	local max_thirst = get_local_val([[gamedata\scripts\actor_status_thirst.script]], "actor_status_thirst", "local start_blur_4") or 5760
	local thirst_mult = get_local_val([[gamedata\scripts\actor_status_thirst.script]], "actor_status_thirst", "local eat_thirstiness_mul") or 1000
	if eat_thirst_ex then
		eat_thirstiness = eat_thirstiness * thirst_mult
		local thirst_clr = eat_thirstiness > 0 and red_clr or green_clr
		local thirst_sign = eat_thirstiness > 0 and "+" or ""
		local thirst_num = (eat_thirstiness / max_thirst) * 100
		str = str .. thirst_clr .. "  • " .. def_clr .. " " .. gc("desc_over_thirst") .. " " .. thirst_clr .. thirst_sign .. round(thirst_num) .. "%" .. def_clr .. " \\n"
		pr("show thirst")
	end

	-- alcohol
	if eat_alc_ex then
		local alco_clr = eat_alcohol > 0 and red_clr or green_clr
		local alco_sign = eat_alcohol > 0 and "+" or ""
		local alco_num = eat_alcohol * 100
		str = str .. alco_clr .. "  • " .. def_clr .. " " .. gc("desc_over_alcohol") .. " " .. alco_clr .. alco_sign .. round(alco_num) .. "%" .. def_clr .. " \\n"
		pr("show alco")
	end

	----------- timed effects -----------

	if boost_time and boost_time ~= 0 then

		-- timed title
		local boost_health_restore = ini_sys:r_float_ex(sec, "boost_health_restore")
		local boost_hp_ex = mcm_hp_t and boost_health_restore and boost_health_restore ~= 0

		local boost_radiation_restore = ini_sys:r_float_ex(sec, "boost_radiation_restore")
		local boost_rad_ex = mcm_rad_t and boost_radiation_restore and boost_radiation_restore ~= 0

		local boost_bleeding_restore = ini_sys:r_float_ex(sec, "boost_bleeding_restore")
		local boost_bleed_ex = mcm_bleed_t and boost_bleeding_restore and boost_bleeding_restore ~= 0

		if (boost_hp_ex or boost_rad_ex or boost_bleed_ex) then
			str = str .. title_clr .. gc("desc_over_timed") .. def_clr .. " \\n"
		end

		-- health
		if boost_hp_ex then
			local thp_clr = boost_health_restore > 0 and green_clr or red_clr
			local thp_sign = boost_health_restore > 0 and "+" or ""
			local thp_num = round(boost_health_restore * 100 * 6 * boost_time)
			str = str .. thp_clr .. "  • " .. def_clr .. " " .. gc("desc_over_hp") .. " " .. thp_clr .. thp_sign .. thp_num .. "%" .. def_clr .. " " .. gc("desc_over_over") .. " " .. round(boost_time) .. " " .. gc("desc_over_sec") .. def_clr .. " \\n"
			pr("show timed hp")
		end

		-- radiation
		if boost_rad_ex then
			local trad_clr = boost_radiation_restore > 0 and green_clr or red_clr
			local trad_sign = boost_radiation_restore > 0 and "-" or ""
			local trad_num = round(boost_radiation_restore * rad_max * 6 * boost_time)
			str = str .. trad_clr .. "  • " .. def_clr .. " " .. gc("desc_over_rad") .. " " .. trad_clr .. trad_sign .. trad_num .. " " .. def_clr .. gc("st_msv") .. " " .. gc("desc_over_over") .. " " .. round(boost_time) .. " " .. gc("desc_over_sec") .. def_clr .. " \\n"
			pr("show timed rad")
		end

		-- bleeding
		if boost_bleed_ex then
			local tbleed_clr = boost_bleeding_restore > 0 and green_clr or red_clr
			local tbleed_sign = boost_bleeding_restore > 0 and "-" or ""
			local tbleed_num = round(boost_bleeding_restore * 100 * 6 * boost_time)
			str = str .. tbleed_clr .. "  • " .. def_clr .. " " .. gc("desc_over_bleed") .. " " .. tbleed_clr .. tbleed_sign .. tbleed_num .. "%" .. def_clr .. " " .. gc("desc_over_over") .. " " .. round(boost_time) .. " " .. gc("desc_over_sec") .. def_clr .. " \\n"
			pr("show timed bleed")
		end

	end


	----------- BHS patch -----------
	if zzz_player_injuries and ( (zzz_player_injuries.medkits and zzz_player_injuries.medkits[sec]) or (zzz_player_injuries.healhelp and zzz_player_injuries.healhelp[sec]) ) then
		str = str .. title_clr .. gc("desc_over_bhs") .. def_clr .. " \\n"
		local bhs_str = bhs_descr_str(obj, sec)
		str = str .. bhs_str
	end

	str = str .. " \\n"

	return str
end

function get_local_val(path, script_name, str_to_find)
	if _G[script_name] then

		if not file_exists(path) then
			return
		end

		for line in io.lines(path) do
			if string.find(line, str_to_find) then
				_,_, loc_val = string.find(line, "start_blur_4%s*=%s*(%d+)")		-- RavenAscendant carried
				if type(tonumber(loc_val)) == "number" then
					return loc_val
				end
			end
		end
	end
end

function file_exists(name)
	local f = io.open(name, "r")
	if f ~= nil then
		io.close(f)
		return true
	else
		return false
	end
end

-- BHS
function bhs_descr_str(obj, obj_sec)

	local _str = ""
	local blue_main = utils_xml.get_color("d_blue")
	local blue_clr = strformat("%c[%s,%s,%s,%s]", 255, 74, 134, 232)
	local yel_clr = strformat("%c[%s,%s,%s,%s]", 0, 252, 186, 3)
	local grey_clr = utils_xml.get_color("ui_gray_2")

	-- get circles/number for string
	local function val_to_fkn_circles(val)
		local circles = ""
		if val >= bhs_display_numeric_at or bhs_show_numeric_always then
			return val
		elseif val > 0 then
			for i = 1, val do
				circles = circles .. gc("st_bhs_mihail_krug")
			end
		end
		return circles
	end

	-- get string
	local function build_string(t_name, sec, color)
		local head_str = ""
		local torso_str = ""
		local arm_str = ""
		local leg_str = ""
		local timeregen_str = ""
		if sec and t_name[sec] then
			for limb, val in pairs(t_name[sec]) do
				if limb == "head" then
					head_str = grey_clr .. gc("st_bhs_head_str") .. color .. val_to_fkn_circles(val) .. " "
				elseif limb == "torso" then
					torso_str = grey_clr .. gc("st_bhs_torso_str") .. color .. val_to_fkn_circles(val) .. " "
				elseif limb == "rightarm" then
					arm_str = grey_clr .. gc("st_bhs_rightarm_str") .. color .. val_to_fkn_circles(val) .. " "
				elseif limb == "rightleg" then
					leg_str = grey_clr .. gc("st_bhs_rightleg_str") .. color .. val_to_fkn_circles(val) .. " "
				elseif limb == "timeregen" and bhs_show_timed_heal_time then
					timeregen_str = grey_clr .. gc("st_bhs_timeregen") .. color .. (val / 1000) .. " "
				end
			end
		end
		local main_string = head_str .. torso_str .. arm_str .. leg_str .. (timeregen_str ~= "" and (" " .. timeregen_str) or "")
--		printf("main_string: [%s]", main_string)
		return main_string
	end

	local medkits_pre = "  " .. yel_clr .. gc("st_bhs_mihail_krug") .. " " .. yel_clr .. " " .. gc("st_bhs_timed_heal") .. "  "
	local medkits_str = build_string(zzz_player_injuries.medkits, obj_sec, yel_clr)
	local healhelp_pre = "  " .. blue_main .. gc("st_bhs_mihail_krug") .. " " .. blue_clr .. " " .. gc("st_bhs_full_heal") .. "  "
	local healhelp_str = build_string(zzz_player_injuries.healhelp, obj_sec, blue_clr)

--		printf("obj_sec: [ %s ] || medkits_str: [ %s ] || healhelp_str: [ %s ]", obj_sec, medkits_str ~= "" and true or false, healhelp_str ~= "" and true or false)
	if medkits_str ~= "" and healhelp_str ~= "" then
		_str = medkits_pre .. medkits_str .. "\\n" .. healhelp_pre .. healhelp_str .. grey_clr .. "\\n"
	elseif medkits_str ~= "" then
		_str = medkits_pre .. medkits_str .. grey_clr .. "\\n"
	elseif healhelp_str ~= "" then
		_str = healhelp_pre .. healhelp_str .. grey_clr .. "\\n"
	end

	return _str
end

function on_option_change()
	mcm_hp = aaa_descr_override_mcm.get_config("hp")
	mcm_rad = aaa_descr_override_mcm.get_config("rad")
	mcm_sat = aaa_descr_override_mcm.get_config("sat")
	mcm_sleep = aaa_descr_override_mcm.get_config("sleep")
	mcm_thirst = aaa_descr_override_mcm.get_config("thirst")
	mcm_alcohol = aaa_descr_override_mcm.get_config("alcohol")

	mcm_hp_t = aaa_descr_override_mcm.get_config("hp_t")
	mcm_rad_t = aaa_descr_override_mcm.get_config("rad_t")
	mcm_bleed_t = aaa_descr_override_mcm.get_config("bleed_t")

	bhs_display_numeric_at = aaa_descr_override_mcm.get_config("bhs_num_at")
	bhs_show_numeric_always = aaa_descr_override_mcm.get_config("bhs_num_always")
	bhs_show_timed_heal_time = aaa_descr_override_mcm.get_config("bhs_timed")
end

function on_game_start()
	RegisterScriptCallback("on_option_change", on_option_change)
end