-- Register this tool
imgui_debug_tools.register_tool("TraderHud", {
    title = "Trader Info",
    render = function()
        render_trader_hud()
    end,
    visible = false
})

function get_nearest_trader(npc)
    local mon
    local dist
    local nearest_stalker,nearest_dist
    local pos
    local st
    for id,st in pairs(db.storage) do
        mon = st.object or level.object_by_id(id)
        if (mon and mon.clsid and mon:clsid() == clsid.script_trader) then
            pos = npc == "cam" and device().cam_pos or mon:position()
            dist = pos:distance_to_sqr(mon:position())
            if not (nearest_dist) then
                nearest_dist = dist
                nearest_stalker = mon
            end

            if (dist < nearest_dist) then
                nearest_dist = dist
                nearest_stalker = mon
            end
        end
    end
    return nearest_stalker,nearest_dist
end

function render_trader_hud()    
    local near = get_nearest_trader("cam")
    if (not near or not near:alive()) then
       ImGui.Text("No trader found nearby")
       return
    end

    local st = db.storage[near:id()]
    if (not st) then
        ImGui.Text("No storage data for trader")
    end

    ImGui.Text("Section Name: " .. tostring(near:section()))
    ImGui.Text("ID: " .. tostring(near:id()))
    ImGui.Text("Name: " .. tostring(near:name()))
    ImGui.Text("Visual: " .. tostring(near:get_visual_name()))
    ImGui.Text("SID: " .. tostring(get_object_story_id(near:id())))
    ImGui.Text("A.Scheme: " .. tostring(st.active_scheme))
    ImGui.Text("A.Section: " .. tostring(st.active_section))
    ImGui.Text("Logic: " .. tostring(st.section_logic))
    ImGui.Text("Ini: " .. tostring(st.ini_filename))
end