-- Register this tool
imgui_debug_tools.register_tool("ActorInsideZoneHud", {
    title = "Actor Inside Zone Info",
    render = function()
        render_actor_inside_zone_hud()
    end,
    visible = false
})

function render_actor_inside_zone_hud()
    if (db.actor and db.actor:alive()) then
        local table_flags = 3 -- Borders(1) + RowBg(2)
        if ImGui.BeginTable("ZoneTable", 3, table_flags, vector2(0, 0), 0) then
            ImGui.TableSetupColumn("ID", 2, 0, 0)
            ImGui.TableSetupColumn("Zone Name", 2, 0, 0) -- 2 = WidthFixed
            ImGui.TableSetupColumn("Section", 2, 0, 0)
            ImGui.TableHeadersRow()
            
            -- Table data
            for _, zone in pairs(db.actor_inside_zones) do
                local st = db.storage[zone:id()]
                ImGui.TableNextRow()
                
                ImGui.TableNextColumn()
                ImGui.Text(tostring(zone:id()))
                
                ImGui.TableNextColumn()
                ImGui.Text(zone:name())
                
                ImGui.TableNextColumn()
                ImGui.Text(st and st.active_section or "")
            end
            
            ImGui.EndTable()
        end
    else
        ImGui.Text("Actor not available or not alive")
    end
end