function on_mcm_load()
    op = { id = "melancholy", gr = 
        {
            { id = "melansurge", sh = true, gr = 
                {
                    {id = "title", type = "slide", link = "ui_options_slider_player", text = "Blowout Options", size = {512, 50}, spacing = 20},
                    {id = "surgetype", type = "radio_v", val = 2, def = 0,
                        content = { 
                            { 0, "surgerandom" }, 
                            { 1, "surgered" }, 
                            { 2, "surgegreen" },
                        }
                    },
                    {id = "stormtype", type = "radio_v", val = 2, def = 0,
                        content = { 
                            { 0, "stormrandom" }, 
                            { 1, "stormblack" }, 
                            { 2, "stormyellow" },
                            { 3, "stormnormal"},                            
                        }
                    },
                }
            }
        }
    }
    return op
end

function get_config(key)
    if ui_mcm then return ui_mcm.get("melansurge/"..key) else return defaults[key] end
end
