function on_mcm_load()
    op = {
        id = "uicellcontainer_optimize", sh = true, gr = {
            { id = "banner", type = "slide", text = "ui_mcm_uicellcontainer_optimize_title", size = { 512, 50 }, spacing = 20 },
            { id = "enabled", type = "check", val = 1, def = true },
            { id = "deferredLimit", type = "track", val = 2, min = 50, max = 500, step = 10, def = 200 },
            { id = "sort_step2", type = "track", val = 2, min = 20, max = 400, step = 20, def = 120 },
            { id = "icon_step", type = "track", val = 2, min = 1, max = 200, step = 5, def = 30 },
        }
    }

    return op
end

function patch()
    -- Time-Sliced Heap Sort, stable time-wise and returns correct item per each call
    -- Heap doesn't need to be fully ordered to start rendering icons, optimal for update loop
    -- @param t: The table to sort
    -- @param order: Optional custom sorting function
    -- @return: A function that you must call repeatedly
    local function create_incremental_sorter(t, order)
        local keys = {}
        local n = 0
        for k in pairs(t) do
            n = n + 1
            keys[n] = k 
        end

        local sift_down
        -- Use order if its provided
        if order then
            sift_down = function(idx, end_idx)
                local hole_idx = idx
                local sifting_key = keys[hole_idx]
                local half_idx = math.floor(end_idx / 2)
                
                while hole_idx <= half_idx do
                    local child = hole_idx * 2
                    
                    if child < end_idx and order(t, keys[child + 1], keys[child]) then
                        child = child + 1
                    end
                    
                    if order(t, keys[child], sifting_key) then
                        keys[hole_idx] = keys[child]
                        hole_idx = child
                    else
                        break
                    end
                end
                keys[hole_idx] = sifting_key
            end
        else
            -- Default alphanumeric sort fallback
            sift_down = function(idx, end_idx)
                local hole_idx = idx
                local sifting_key = keys[hole_idx]
                local half_idx = math.floor(end_idx / 2)
                
                while hole_idx <= half_idx do
                    local child = hole_idx * 2
                    
                    if child < end_idx and keys[child + 1] < keys[child] then
                        child = child + 1
                    end
                    
                    if keys[child] < sifting_key then
                        keys[hole_idx] = keys[child]
                        hole_idx = child
                    else
                        break
                    end
                end
                keys[hole_idx] = sifting_key
            end
        end

        local heap_i = math.floor(n / 2)
        local heap_built = (n <= 1)

        -- create_incremental_sorter returns this function
        -- returns:
        --  false/true indicating the work is done
        --  index and data retrieved from the heap when its built
        --  index and data Will be nil on first few calls so need to check them in the Update loop
        -- It must be called in Update loop to retrieve next item if until its done
        return function()
            -- Build the heap first
            if not heap_built then
                if heap_i >= 1 then
                    sift_down(heap_i, n)
                    heap_i = heap_i - 1
                    if heap_i < 1 then
                       heap_built = true
                    end
                end

                -- Return 'false' but no item yet; we are still preparing the data
                return false 
            end

            while n > 0 do
                local best_key = keys[1]
                local val = t[best_key]

                -- Pop from heap
                keys[1] = keys[n]
                keys[n] = nil
                n = n - 1

                if n > 0 then
                    sift_down(1, n)
                end

                -- If the item still exists, return it. 
                -- If not, the 'while' loop continues to the next best item.
                if val ~= nil then
                    return false, best_key, val
                end
            end

            return true
        end
    end

    -- Batch processing of items in UICellContainer
    utils_ui.UICellContainer.InitDeferredDisplayData = function(self)
        if self.deferredInitialized then return end
        self.deferredInitialized = true

        self.itemsData = {} -- Data for items since vanilla sort functions expect t with just obj and section, actual data will be stored there
        self.itemsMap = {} -- obj:id() -> index in t map to prevent duplicates
        self.t = {} -- reference to t argument

        self.sorter = nil
        self.sort_order = nil
        self.original_sort_order = nil
        self.sorterUpdateTime = 0

        self.deferredLimit = self:GetDeferredLimit() -- If size of t is less than this, display it normally at once
        self.deferred = nil -- nil means first frame check will be done that will set to true or false

        self.addItemKey = 65537 -- Key for newly added items in case of if incoming t is id -> obj map to not overwrite values, incremented by 1 with each addItem call

        -- Dynamic step will be calculated depending on current frametime
        self.sort_step = self:CalcSortStep()
        self.icon_step = self:CalcIconStep()

        -- Callback if object was destroyed mid-sort
        RegisterScriptCallback("game_object_on_net_destroy", self)

        -- Patch owner's Show function
        if self.owner then
            if not self.owner.defferedPatched then
                self.owner.defferedPatched = true
                self.owner.deferredCC = {}
                local show = self.owner.Show
                self.owner.Show = function(self, state, ...)
                    if not state then
                        for k in pairs(self.deferredCC) do
                            -- Reset sorting if it happens, the UICellContainer should handle AddItem duplicates if they happen
                            k:ResetSorter(true)
                        end
                    end
                    return show(self, state, ...)
                end
            end
            self.owner.deferredCC[self] = true
        end

        ----------------- seax patch begin
        self.original_FindFreeCell = self.FindFreeCell
        ----------------- seax patch end

        -- Progress icon
        local xml = CScriptXmlInit()
        xml:ParseFile("ui_inventory_antifreeze.xml")
        self.deferredIcon = xml:InitStatic("poarch_cringe_seq", self.prof)
        self.deferredIcon:Show(false)

        local contSizeHeight = self.prof:GetHeight()
        local contSizeWidth = self.prof:GetWidth()
        local iconWidth = self.deferredIcon:GetWidth()
        local iconHeight = self.deferredIcon:GetHeight()

        -- Calculate available space with padding on all sides
        local padding = 32
        local maxSize = 128 + padding * 2
        local availWidth = math.max(math.min(maxSize, contSizeWidth) - padding * 2, 0)
        local availHeight = math.max(math.min(maxSize, contSizeHeight) - padding * 2, 0)

        -- Determine the scale factor (S = min(availW/iconW, availH/iconH))
        -- This ensures the icon shrinks to fit the smallest dimension available
        local scale = math.min(1, math.min(availWidth / iconWidth, availHeight / iconHeight))

        -- Set the calculated size
        local newWidth = iconWidth * scale
        local newHeight = iconHeight * scale
        self.deferredIcon:SetWndSize(vector2():set(newWidth, newHeight))

        -- Center the icon
        local posX = contSizeWidth / 2
        local posY = contSizeHeight  / 2
        self.deferredIcon:SetWndPos(vector2():set(posX, posY))
    end

    -- With less fps, more work will be done to keep it consistent
    utils_ui.UICellContainer.CalcSortStep = function(self)
        return (ui_mcm and ui_mcm.get("uicellcontainer_optimize/sort_step2") or 120) * math.min(4, device().time_delta / 16) 
    end

    utils_ui.UICellContainer.CalcIconStep = function(self)
        return (ui_mcm and ui_mcm.get("uicellcontainer_optimize/icon_step") or 30) * math.min(4, device().time_delta / 16) 
    end

    utils_ui.UICellContainer.GetDeferredLimit = function(self)
        return ui_mcm and ui_mcm.get("uicellcontainer_optimize/deferredLimit") or 200
    end

    utils_ui.UICellContainer.GetDeferredEnabled = function(self)
        if ui_mcm then
            return ui_mcm.get("uicellcontainer_optimize/enabled")
        end
        return true
    end

    utils_ui.UICellContainer.InvalidateDeferredDisplay = function(self)
        if not self.deferredInitialized then return end
        empty_table(self.itemsData)
        empty_table(self.itemsMap)
        self.t = {} -- force new table so it won't empty other reference
        self.sorter = nil
        self.sort_order = nil
        self.original_sort_order = nil
        self.sorterUpdateTime = 0
        self.addItemKey = 65537

        ----------------- seax patch begin
        self.FindFreeCell = self.original_FindFreeCell
        ----------------- seax patch end

        RemoveTimeEvent("cellContainerDeferredIconShow", self.ID)
        RemoveTimeEvent("cellContainerDeferredSorterUpdate", self.ID)
        self.deferredIcon:Show(false)
    end

    utils_ui.UICellContainer.ResetSorter = function(self, checkIfSet)
        if not self.deferredInitialized then return end


        if not checkIfSet or self.sorter then
            local tg = time_continual()

            -- Update once immediately if time is different, remove existing time event
            if tg > self.sorterUpdateTime then
                RemoveTimeEvent("cellContainerDeferredSorterUpdate", self.ID)
                self.sorterUpdateTime = tg
                self.sort_order = self:GetSortOrder(self.t, self.original_sort_order)
                self.sorter = create_incremental_sorter(self.t, self.original_sort_order)
            -- Aggregate consecutive updates and perform on next frame to reduce call frequency
            elseif tg == self.sorterUpdateTime then
                CreateTimeEvent("cellContainerDeferredSorterUpdate", self.ID, 0, function()
                    self.sort_order = self:GetSortOrder(self.t, self.original_sort_order)
                    self.sorter = create_incremental_sorter(self.t, self.original_sort_order)
                    return true
                end)
            end
        end
    end

    utils_ui_UICellContainer_InitControls = utils_ui.UICellContainer.InitControls
    utils_ui.UICellContainer.InitControls = function(self, ...)
        utils_ui_UICellContainer_InitControls(self, ...)
        self:InitDeferredDisplayData()
    end

    utils_ui_UICellContainer_finalize = utils_ui.UICellContainer.__finalize
    utils_ui.UICellContainer.__finalize = function(self)
        if self.owner and self.owner.deferredCC then
            self.owner.deferredCC[self] = nil
        end
        if utils_ui_UICellContainer_finalize then
            utils_ui_UICellContainer_finalize(self)
        end
    end

    utils_ui_UICellContainer_AddItem = utils_ui.UICellContainer.AddItem
    utils_ui.UICellContainer.AddItem = function(self, obj, sec, ...)
        if self.deferred == false then
            return utils_ui_UICellContainer_AddItem(self, obj, sec, ...)
        end

        if (not sec) then
            if (not obj) then
                return
            end
            sec = obj and obj:section()
        end

        -- Duplicate data check
        local id = obj and obj:id()
        if id and self.itemsMap[id] then
            return
        end

        local i = self.addItemKey
        self.addItemKey = self.addItemKey + 1
        if id then
            self.itemsMap[id] = i
        end
        self.t[i] = obj or sec
        self.itemsData[i] = {obj, sec, ...}

        self:ResetSorter(false)
    end

    utils_ui.UICellContainer.GetSortOrder = function(self, t, sort_order)
        ----------------- seax patch begin
        if seax_sortingplus_opt_sort_by_kind and seax_sortingplus_opt_sort_by_kind.sort_by_kind_factory then
            if self.sort_method == "kind" then
                sort_by_kind_custom, patched_custom_FindFreeCell = seax_sortingplus_opt_sort_by_kind.sort_by_kind_factory(t)

                sort_order = sort_by_kind_custom
                -- kinda dirty but the overrided FindFreeCell in zzz_rax_sortingplus_mcm references
                -- state that is built up during its sort functions so we need to do the same
                -- just do it for this specific sort though and clean up after ourselves.
                self.FindFreeCell = patched_custom_FindFreeCell
            end
        end
        ----------------- seax patch end

        -- Safety wrapper
        return function(t, a, b)
            local va = t[a]
            local vb = t[b]
            if va == nil then return false end -- 'a' is nil, so 'b' is "better"
            if vb == nil then return true end  -- 'b' is nil, so 'a' is "better"
            return sort_order(t, a, b)
        end
    end

    utils_ui_UICellContainer_Reinit = utils_ui.UICellContainer.Reinit
    utils_ui.UICellContainer.Reinit = function(self, t, tf, ...)
        self:InitDeferredDisplayData()
        self:InvalidateDeferredDisplay()
        
        utils_ui_UICellContainer_Reinit(self, {}, tf, ...)

        if not t then
            self.deferred = false
            return
        end

        -- With less fps, more work will be done to keep it consistent
        self.sort_step = self:CalcSortStep()
        self.icon_step = self:CalcIconStep()
        self.deferredLimit = self:GetDeferredLimit()

        -- Create cells
        self.ignore_scroll = true
        self:Print(nil, "Reset | START Number of cells: %s", #self.cell)
        
        local sort_order = self:GetSortMethod()
        sort_order = self:GetSortOrder(t, sort_order)
        self.original_sort_order = sort_order

        -- Init deferred display only on big data and not showcase
        if not self:GetDeferredEnabled() or self.showcase or size_table(t) < self.deferredLimit then
            self.deferred = false
            if self.showcase then
                for i,sec in spairs(t, sort_order) do
                    utils_ui_UICellContainer_AddItem(self, nil, sec, tf and tf[i])
                end
            else
                for i,obj in spairs(t, sort_order) do
                    utils_ui_UICellContainer_AddItem(self, obj, nil, tf and tf[i])
                end
            end

            ----------------- seax patch begin
            self.FindFreeCell = self.original_FindFreeCell
            ----------------- seax patch end

        else
            self.sort_order = sort_order
            self.t = t
            self:ResetSorter(false)
            self.deferred = true

            -- Postpone icon showing for some time so it won't flicker
            RemoveTimeEvent("cellContainerDeferredIconShow", self.ID)
            CreateTimeEvent("cellContainerDeferredIconShow", self.ID, 0.1, function()
                self.deferredIcon:Show(true)
                return true
            end)

            for i, obj in pairs(t) do
                self.itemsMap[obj:id()] = i
                self.itemsData[i] = {obj, nil, tf and tf[i]}
            end
        end
        
        self.ignore_scroll = false
        self:Print(nil, "Reset | END Number of cells: %s", #self.cell)
        
        self:Scroll_Reinit()
    end

    utils_ui_UICellContainer_Update = utils_ui.UICellContainer.Update
    utils_ui.UICellContainer.Update = function(self, ...)
        if not self.sorter then
            return utils_ui_UICellContainer_Update(self, ...)
        end

        -- Use sort_step for building heap, and icon_step for getting items
        -- First call will determine if its in build mode or draw mode by having i not nil
        local done, i = self.sorter()
        if not done then
            local j = 1
            if not i then
                while j < self.sort_step do
                    done, i = self.sorter()
                    -- Move to draw mode with icon_step, hide loading icon
                    -- If we spent a lot of time finalizing building the heap, the j will be larger than icon_step so it will draw only one icon and move to the next frame
                    if i then
                        RemoveTimeEvent("cellContainerDeferredIconShow", self.ID)
                        self.deferredIcon:Show(false)
                        break
                    end
                    j = j + 1
                end
            end
            if i then
                local data = self.itemsData[i]
                utils_ui_UICellContainer_AddItem(self, unpack(data))
                while j < self.icon_step do
                    done, i = self.sorter()
                    if not done then
                        local data = self.itemsData[i]
                        utils_ui_UICellContainer_AddItem(self, unpack(data))
                    else
                        break
                    end
                    j = j + 1
                end
            end
        end

        -- Do stuff when work is done
        if done then
            self:Scroll_Reinit(true)

            -- Disable deferred mode, the work is done
            self:InvalidateDeferredDisplay()
            self.deferred = false

            -- Inventory specific updates
            if self.owner and self.owner.isInventoryGUI then
                ui_inventory.GUI:Picker_Refresh()
                ui_inventory.GUI:UnHighlight_All()
            end

            -- Sorting Plus patch
            if self.owner and self.owner.isInventoryGUI 
            and ui_inventory.GUI.CC["actor_trade_bag"] and self.ID == ui_inventory.GUI.CC["actor_trade_bag"].ID
            and ui_inventory.GUI.SortJunkTradeReady and ui_inventory.GUI.SortJunkTrade 
            and zzz_rax_sortingplus_mcm
            then
                ui_inventory.GUI.SortJunkTradeReady = false
                if ui_inventory.GUI.mode == "trade" and zzz_rax_sortingplus_mcm.AUTOSELLJUNK then 
                    ui_inventory.GUI:SortJunkTrade()
                end
            end

            -- Unusable Parts Handler patch
            if unusable_parts_handler then
                unusable_parts_handler.GUI_on_show("UIInventory")
            end
        end

        return utils_ui_UICellContainer_Update(self, ...)
    end

    utils_ui_UICellContainer_Show = utils_ui.UICellContainer.Show
    utils_ui.UICellContainer.Show = function(self, state, ...)
        if not state then
            self:ResetSorter(true)
        end

        return utils_ui_UICellContainer_Show(self, state, ...)
    end

    utils_ui.UICellContainer.RemoveAndInvalidate = function(self, obj)
        local found = false

        -- Quick lookup first, then try full pass
        local i = self.itemsMap[obj:id()]
        local data = i and self.t[i]
        if data and data.id and data:id() == obj:id() then
            self.t[i] = nil
            self.itemsData[i] = nil
            found = true
        else
            for i, data in pairs(self.t) do
                if data.id and data:id() == obj:id() then
                    self.t[i] = nil
                    self.itemsData[i] = nil
                    found = true
                end
            end
        end
        self.itemsMap[obj:id()] = nil

        -- Reset sorting if it happens, the UICellContainer should handle AddItem duplicates if they happen
        if found then
            self:ResetSorter(true)
        end
    end

    utils_ui_UICellContainer_RemoveItem = utils_ui.UICellContainer.RemoveItem
    utils_ui.UICellContainer.RemoveItem = function(self, obj, sec, ...)
        if obj then
            self:RemoveAndInvalidate(obj)
        end
        utils_ui_UICellContainer_RemoveItem(self, obj, sec, ...)
    end

    utils_ui.UICellContainer.game_object_on_net_destroy = function(self, obj)
        self:RemoveItem(obj, obj:section())
    end

    utils_ui_UICellContainer_TransferItem = utils_ui.UICellContainer.TransferItem
    utils_ui.UICellContainer.TransferItem = function(self, cont_to, ...)
        -- Temporary override function to use initial version
        local f = cont_to.AddItem
        cont_to.AddItem = utils_ui_UICellContainer_AddItem
        local result = utils_ui_UICellContainer_TransferItem(self, cont_to, ...)
        cont_to.AddItem = f
        return result
    end
end

function GUI_on_show(name)
    if (name ~= "UIInventory") then return end
    ui_inventory.GUI.isInventoryGUI = true
    ui_inventory.GUI.SortJunkTradeReady = true
end

function GUI_on_hide(name)
    if (name ~= "UIInventory") then return end
    ui_inventory.GUI.SortJunkTradeReady = false
end

function on_game_start()
    patch()
    RegisterScriptCallback("GUI_on_show", GUI_on_show)
    RegisterScriptCallback("GUI_on_hide", GUI_on_hide)
end
