-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets
    
o["wpn_m4a1_siber"] = {
    x = 0.050000000745058,
    y = 0.18000000715256,
    z = 0.050000000745058,
}
end